all: alg1 alg2 alg3

alg1: src/tablice_alg_1.cpp 
	g++ -Wall -pedantic -std=c++0x src/tablice_alg_1.cpp -o alg1

alg2: src/tablice_alg_2.cpp 
	g++ -Wall -pedantic -std=c++0x src/tablice_alg_2.cpp -o alg2

alg3: src/tablice_alg_3.cpp 
	g++ -Wall -pedantic -std=c++0x src/tablice_alg_3.cpp -o alg3

clean:
	rm alg1 alg2 alg3
